services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: micanopy-backend
    ports:
      - "3001:3001"
    volumes:
      - pending:/pending
      - uploads:/uploads
    env_file:
      - prod.env
    image: backend_image
    networks:
      - micanopy-network

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: micanopy-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    image: frontend_image
    networks:
      - micanopy-network

networks:
  micanopy-network:
    driver: bridge

volumes:
  pending:
  uploads:
