version: "3.9"

services:
  #We will put our code for building the backend here
  # backend:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   container_name: micanopy-backend
  #   ports:
  #     - "5000:5000"
  #   env_file:
  #     - prod.env
  #   image: backend_image

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: micanopy-frontend
    ports:
      - "8080:80"
    # depends_on:
    #   - backend
    image: frontend_image