services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: micanopy-backend
    ports:
      - "3002:3001"
    env_file:
      - server/.env
    image: micanopy-backend
    networks:
      - micanopy-network

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: micanopy-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    image: frontend_image
    networks:
      - micanopy-network

networks:
  micanopy-network:
    driver: bridge
